package cpu

func init() {
	ld(sp.Write(), paramW())
}

func createOpCodeTable() opCodeTable {
	extTbl := createExtendedOpCodeTable()

	return opCodeTable{
		/* 0x00 */ labeled{"NOP", nop()},
		/* 0x01 */ labeled{"LD BC, nn", ld(bc.Write(), paramW())},
		/* 0x02 */ labeled{"LD (BC), A", ld(bc.Deref().Write(), a.Read())},
		/* 0x03 */ labeled{"INC BC", incR16(bc)},
		/* 0x04 */ labeled{"INC B", incR8(b)},
		/* 0x05 */ labeled{"DEC B", decR8(b)},
		/* 0x06 */ labeled{"LD B, n", ld(b.Write(), paramB())},
		/* 0x07 */ labeled{"RLCA", rlca()},
		/* 0x08 */ labeled{"LD (nn), SP", pipe(sp.Read(), paramW(), writeWord())},
		/* 0x09 */ labeled{"ADD HL, BC", addR16(hl, bc)},
		/* 0x0A */ labeled{"LD A, (BC)", ld(a.Write(), bc.Deref().Read())},
		/* 0x0B */ labeled{"DEC BC", decR16(bc)},
		/* 0x0C */ labeled{"INC C", incR8(c)},
		/* 0x0D */ labeled{"DEC C", decR8(c)},
		/* 0x0E */ labeled{"LD C, n", ld(c.Write(), paramB())},
		/* 0x0F */ labeled{"RRC A", rrca()},
		/* 0x10 */ labeled{"STOP", stop()},
		/* 0x11 */ labeled{"LD DE, nn", ld(de.Write(), paramW())},
		/* 0x12 */ labeled{"LD (DE), A", ld(de.Deref().Write(), a.Read())},
		/* 0x13 */ labeled{"INC DE", incR16(de)},
		/* 0x14 */ labeled{"INC D", incR8(d)},
		/* 0x15 */ labeled{"DEC D", decR8(d)},
		/* 0x16 */ labeled{"LD D, n", ld(d.Write(), paramB())},
		/* 0x17 */ labeled{"RLA", rla()},
		/* 0x18 */ labeled{"JR n", jr(flag(0), false)},
		/* 0x19 */ labeled{"ADD HL, DE", addR16(hl, de)},
		/* 0x1A */ labeled{"LD A, (DE)", ld(a.Write(), de.Deref().Read())},
		/* 0x1B */ labeled{"DEC DE", decR16(de)},
		/* 0x1C */ labeled{"INC E", incR8(e)},
		/* 0x1D */ labeled{"DEC E", decR8(e)},
		/* 0x1E */ labeled{"LD E, n", ld(e.Write(), paramB())},
		/* 0x1F */ labeled{"RRA", rra()},
		/* 0x20 */ labeled{"JR NZ, n", jr(zero, true)},
		/* 0x21 */ labeled{"LD HL, nn", ld(hl.Write(), paramW())},
		/* 0x22 */ labeled{"LDI (HL), A", pipe(a.Read(), hl.Deref().Write(), incHLFast())},
		/* 0x23 */ labeled{"INC HL", incR16(hl)},
		/* 0x24 */ labeled{"INC H", incR8(h)},
		/* 0x25 */ labeled{"DEC H", decR8(h)},
		/* 0x26 */ labeled{"LD H,n", ld(h.Write(), paramB())},
		/* 0x27 */ labeled{"DAA", daa()},
		/* 0x28 */ labeled{"JR Z, n", jr(zero, false)},
		/* 0x29 */ labeled{"ADD HL, HL", addR16(hl, hl)},
		/* 0x2A */ labeled{"LDI A, (HL)", pipe(hl.Deref().Read(), a.Write(), incHLFast())},
		/* 0x2B */ labeled{"DEC HL", decR16(hl)},
		/* 0x2C */ labeled{"INC L", incR8(l)},
		/* 0x2D */ labeled{"DEC L", decR8(l)},
		/* 0x2E */ labeled{"LD L, n", ld(l.Write(), paramB())},
		/* 0x2F */ labeled{"CPL", cpl()},
		/* 0x30 */ labeled{"JR NC, n", jr(carry, true)},
		/* 0x31 */ labeled{"LD SP, nn", ld(sp.Write(), paramW())},
		/* 0x32 */ labeled{"LDD (HL), A", pipe(a.Read(), hl.Deref().Write(), decHLFast())},
		/* 0x33 */ labeled{"INC SP", incR16(sp)},
		/* 0x34 */ labeled{"INC (HL)", incR8(hl.Deref())},
		/* 0x35 */ labeled{"DEC (HL)", decR8(hl.Deref())},
		/* 0x36 */ labeled{"LD (HL), n", ld(hl.Deref().Write(), paramB())},
		/* 0x37 */ labeled{"SCF", scf()},
		/* 0x38 */ labeled{"JR C, n", jr(carry, false)},
		/* 0x39 */ labeled{"ADD HL, SP", addR16(hl, sp)},
		/* 0x3A */ labeled{"LDD A, (HL)", pipe(hl.Deref().Read(), a.Write(), decHLFast())},
		/* 0x3B */ labeled{"DEC SP", decR16(sp)},
		/* 0x3C */ labeled{"INC A", incR8(a)},
		/* 0x3D */ labeled{"DEC A", decR8(a)},
		/* 0x3E */ labeled{"LD A, n", ld(a.Write(), paramB())},
		/* 0x3F */ labeled{"CCFx", ccf()},
		/* 0x40 */ labeled{"LD B, B", ld(b.Write(), b.Read())},
		/* 0x41 */ labeled{"LD B, C", ld(b.Write(), c.Read())},
		/* 0x42 */ labeled{"LD B, D", ld(b.Write(), d.Read())},
		/* 0x43 */ labeled{"LD B, E", ld(b.Write(), e.Read())},
		/* 0x44 */ labeled{"LD B, H", ld(b.Write(), h.Read())},
		/* 0x45 */ labeled{"LD B, L", ld(b.Write(), l.Read())},
		/* 0x46 */ labeled{"LD B, (HL)", ld(b.Write(), hl.Deref().Read())},
		/* 0x47 */ labeled{"LD B, A", ld(b.Write(), a.Read())},
		/* 0x48 */ labeled{"LD C, B", ld(c.Write(), b.Read())},
		/* 0x49 */ labeled{"LD C, C", ld(c.Write(), c.Read())},
		/* 0x4A */ labeled{"LD C, D", ld(c.Write(), d.Read())},
		/* 0x4B */ labeled{"LD C, E", ld(c.Write(), e.Read())},
		/* 0x4C */ labeled{"LD C, H", ld(c.Write(), h.Read())},
		/* 0x4D */ labeled{"LD C, L", ld(c.Write(), l.Read())},
		/* 0x4E */ labeled{"LD C, (HL)", ld(c.Write(), hl.Deref().Read())},
		/* 0x4F */ labeled{"LD C, A", ld(c.Write(), a.Read())},
		/* 0x50 */ labeled{"LD D, B", ld(d.Write(), b.Read())},
		/* 0x51 */ labeled{"LD D, C", ld(d.Write(), c.Read())},
		/* 0x52 */ labeled{"LD D, D", ld(d.Write(), d.Read())},
		/* 0x53 */ labeled{"LD D, E", ld(d.Write(), e.Read())},
		/* 0x54 */ labeled{"LD D, H", ld(d.Write(), h.Read())},
		/* 0x55 */ labeled{"LD D, L", ld(d.Write(), l.Read())},
		/* 0x56 */ labeled{"LD D, (HL)", ld(d.Write(), hl.Deref().Read())},
		/* 0x57 */ labeled{"LD D, A", ld(d.Write(), a.Read())},
		/* 0x58 */ labeled{"LD E, B", ld(e.Write(), b.Read())},
		/* 0x59 */ labeled{"LD E, C", ld(e.Write(), c.Read())},
		/* 0x5A */ labeled{"LD E, D", ld(e.Write(), d.Read())},
		/* 0x5B */ labeled{"LD E, E", ld(e.Write(), e.Read())},
		/* 0x5C */ labeled{"LD E, H", ld(e.Write(), h.Read())},
		/* 0x5D */ labeled{"LD E, L", ld(e.Write(), l.Read())},
		/* 0x5E */ labeled{"LD E, (HL)", ld(e.Write(), hl.Deref().Read())},
		/* 0x5F */ labeled{"LD E, A", ld(e.Write(), a.Read())},
		/* 0x60 */ labeled{"LD H, B", ld(h.Write(), b.Read())},
		/* 0x61 */ labeled{"LD H, C", ld(h.Write(), c.Read())},
		/* 0x62 */ labeled{"LD H, D", ld(h.Write(), d.Read())},
		/* 0x63 */ labeled{"LD H, E", ld(h.Write(), e.Read())},
		/* 0x64 */ labeled{"LD H, H", ld(h.Write(), h.Read())},
		/* 0x65 */ labeled{"LD H, L", ld(h.Write(), l.Read())},
		/* 0x66 */ labeled{"LD H, (HL)", ld(h.Write(), hl.Deref().Read())},
		/* 0x67 */ labeled{"LD H, A", ld(h.Write(), a.Read())},
		/* 0x68 */ labeled{"LD L, B", ld(l.Write(), b.Read())},
		/* 0x69 */ labeled{"LD L, C", ld(l.Write(), c.Read())},
		/* 0x6A */ labeled{"LD L, D", ld(l.Write(), d.Read())},
		/* 0x6B */ labeled{"LD L, E", ld(l.Write(), e.Read())},
		/* 0x6C */ labeled{"LD L, H", ld(l.Write(), h.Read())},
		/* 0x6D */ labeled{"LD L, L", ld(l.Write(), l.Read())},
		/* 0x6E */ labeled{"LD L, (HL)", ld(l.Write(), hl.Deref().Read())},
		/* 0x6F */ labeled{"LD L, A", ld(l.Write(), a.Read())},
		/* 0x70 */ labeled{"LD (HL), B", ld(hl.Deref().Write(), b.Read())},
		/* 0x71 */ labeled{"LD (HL), C", ld(hl.Deref().Write(), c.Read())},
		/* 0x72 */ labeled{"LD (HL), D", ld(hl.Deref().Write(), d.Read())},
		/* 0x73 */ labeled{"LD (HL), E", ld(hl.Deref().Write(), e.Read())},
		/* 0x74 */ labeled{"LD (HL), H", ld(hl.Deref().Write(), h.Read())},
		/* 0x75 */ labeled{"LD (HL), L", ld(hl.Deref().Write(), l.Read())},
		/* 0x76 */ labeled{"HALT", halt()},
		/* 0x77 */ labeled{"LD (HL), A", ld(hl.Deref().Write(), a.Read())},
		/* 0x78 */ labeled{"LD A, B", ld(a.Write(), b.Read())},
		/* 0x79 */ labeled{"LD A, C", ld(a.Write(), c.Read())},
		/* 0x7A */ labeled{"LD A, D", ld(a.Write(), d.Read())},
		/* 0x7B */ labeled{"LD A, E", ld(a.Write(), e.Read())},
		/* 0x7C */ labeled{"LD A, H", ld(a.Write(), h.Read())},
		/* 0x7D */ labeled{"LD A, L", ld(a.Write(), l.Read())},
		/* 0x7E */ labeled{"LD A, (HL)", ld(a.Write(), hl.Deref().Read())},
		/* 0x7F */ labeled{"LD A, A", ld(a.Write(), a.Read())},
		/* 0x80 */ labeled{"ADD A, B", addR8(a, b.Read())},
		/* 0x81 */ labeled{"ADD A, C", addR8(a, c.Read())},
		/* 0x82 */ labeled{"ADD A, D", addR8(a, d.Read())},
		/* 0x83 */ labeled{"ADD A, E", addR8(a, e.Read())},
		/* 0x84 */ labeled{"ADD A, H", addR8(a, h.Read())},
		/* 0x85 */ labeled{"ADD A, L", addR8(a, l.Read())},
		/* 0x86 */ labeled{"ADD A, (HL)", addR8(a, hl.Deref().Read())},
		/* 0x87 */ labeled{"ADD A, A", addR8(a, a.Read())},
		/* 0x88 */ labeled{"ADC A, B", adcR8(a, b.Read())},
		/* 0x89 */ labeled{"ADC A, C", adcR8(a, c.Read())},
		/* 0x8A */ labeled{"ADC A, D", adcR8(a, d.Read())},
		/* 0x8B */ labeled{"ADC A, E", adcR8(a, e.Read())},
		/* 0x8C */ labeled{"ADC A, H", adcR8(a, h.Read())},
		/* 0x8D */ labeled{"ADC A, L", adcR8(a, l.Read())},
		/* 0x8E */ labeled{"ADC A, (HL)", adcR8(a, hl.Deref().Read())},
		/* 0x8F */ labeled{"ADC A, A", adcR8(a, a.Read())},
		/* 0x90 */ labeled{"SUB A, B", subR8(a, b.Read())},
		/* 0x91 */ labeled{"SUB A, C", subR8(a, c.Read())},
		/* 0x92 */ labeled{"SUB A, D", subR8(a, d.Read())},
		/* 0x93 */ labeled{"SUB A, E", subR8(a, e.Read())},
		/* 0x94 */ labeled{"SUB A, H", subR8(a, h.Read())},
		/* 0x95 */ labeled{"SUB A, L", subR8(a, l.Read())},
		/* 0x96 */ labeled{"SUB A, (HL)", subR8(a, hl.Deref().Read())},
		/* 0x97 */ labeled{"SUB A, A", subR8(a, a.Read())},
		/* 0x98 */ labeled{"SBC A, B", sbcR8(a, b.Read())},
		/* 0x99 */ labeled{"SBC A, C", sbcR8(a, c.Read())},
		/* 0x9A */ labeled{"SBC A, D", sbcR8(a, d.Read())},
		/* 0x9B */ labeled{"SBC A, E", sbcR8(a, e.Read())},
		/* 0x9C */ labeled{"SBC A, H", sbcR8(a, h.Read())},
		/* 0x9D */ labeled{"SBC A, L", sbcR8(a, l.Read())},
		/* 0x9E */ labeled{"SBC A, (HL)", sbcR8(a, hl.Deref().Read())},
		/* 0x9F */ labeled{"SBC A, A", sbcR8(a, a.Read())},
		/* 0xA0 */ labeled{"AND B", andR8(a, b.Read())},
		/* 0xA1 */ labeled{"AND C", andR8(a, c.Read())},
		/* 0xA2 */ labeled{"AND D", andR8(a, d.Read())},
		/* 0xA3 */ labeled{"AND E", andR8(a, e.Read())},
		/* 0xA4 */ labeled{"AND H", andR8(a, h.Read())},
		/* 0xA5 */ labeled{"AND L", andR8(a, l.Read())},
		/* 0xA6 */ labeled{"AND (HL)", andR8(a, hl.Deref().Read())},
		/* 0xA7 */ labeled{"AND A", andR8(a, a.Read())},
		/* 0xA8 */ labeled{"XOR B", xorR8(a, b.Read())},
		/* 0xA9 */ labeled{"XOR C", xorR8(a, c.Read())},
		/* 0xAA */ labeled{"XOR D", xorR8(a, d.Read())},
		/* 0xAB */ labeled{"XOR E", xorR8(a, e.Read())},
		/* 0xAC */ labeled{"XOR H", xorR8(a, h.Read())},
		/* 0xAD */ labeled{"XOR L", xorR8(a, l.Read())},
		/* 0xAE */ labeled{"XOR (HL)", xorR8(a, hl.Deref().Read())},
		/* 0xAF */ labeled{"XOR A", xorR8(a, a.Read())},
		/* 0xB0 */ labeled{"OR B", orR8(a, b.Read())},
		/* 0xB1 */ labeled{"OR C", orR8(a, c.Read())},
		/* 0xB2 */ labeled{"OR D", orR8(a, d.Read())},
		/* 0xB3 */ labeled{"OR E", orR8(a, e.Read())},
		/* 0xB4 */ labeled{"OR H", orR8(a, h.Read())},
		/* 0xB5 */ labeled{"OR L", orR8(a, l.Read())},
		/* 0xB6 */ labeled{"OR (HL)", orR8(a, hl.Deref().Read())},
		/* 0xB7 */ labeled{"OR A", orR8(a, a.Read())},
		/* 0xB8 */ labeled{"CP B", cpR8(a, b.Read())},
		/* 0xB9 */ labeled{"CP C", cpR8(a, c.Read())},
		/* 0xBA */ labeled{"CP D", cpR8(a, d.Read())},
		/* 0xBB */ labeled{"CP E", cpR8(a, e.Read())},
		/* 0xBC */ labeled{"CP H", cpR8(a, h.Read())},
		/* 0xBD */ labeled{"CP L", cpR8(a, l.Read())},
		/* 0xBE */ labeled{"CP (HL)", cpR8(a, hl.Deref().Read())},
		/* 0xBF */ labeled{"CP A", cpR8(a, a.Read())},
		/* 0xC0 */ labeled{"RET NZ", ret(zero, true)},
		/* 0xC1 */ labeled{"POP BC", pop(bc)},
		/* 0xC2 */ labeled{"JP NZ, nn", jp(zero, true)},
		/* 0xC3 */ labeled{"JP nn", jp(flag(0), false)},
		/* 0xC4 */ labeled{"CALL NZ, nn", call(zero, true)},
		/* 0xC5 */ labeled{"PUSH BC", push(bc)},
		/* 0xC6 */ labeled{"ADD A, n", addR8(a, paramB())},
		/* 0xC7 */ labeled{"RST 0 ", rst(0x00)},
		/* 0xC8 */ labeled{"RET Z", ret(zero, false)},
		/* 0xC9 */ labeled{"RET", pipe(pop(pc), delay{})},
		/* 0xCA */ labeled{"JP Z, nn", jp(zero, false)},
		/* 0xCB */ pipe(paramB(), extTbl), // Extended OpCodes
		/* 0xCC */ labeled{"CALL Z, nn", call(zero, false)},
		/* 0xCD */ labeled{"CALL nn", call(flag(0), false)},
		/* 0xCE */ labeled{"ADC A, n", adcR8(a, paramB())},
		/* 0xCF */ labeled{"RST 8 ", rst(0x08)},
		/* 0xD0 */ labeled{"RET NC", ret(carry, true)},
		/* 0xD1 */ labeled{"POP DE", pop(de)},
		/* 0xD2 */ labeled{"JP NC, nn", jp(carry, true)},
		/* 0xD3 */ labeled{"INVALID OPCODE", invalid()},
		/* 0xD4 */ labeled{"CALL NC, nn", call(carry, true)},
		/* 0xD5 */ labeled{"PUSH DE", push(de)},
		/* 0xD6 */ labeled{"SUB A, n", subR8(a, paramB())},
		/* 0xD7 */ labeled{"RST 10", rst(0x10)},
		/* 0xD8 */ labeled{"RET C", ret(carry, false)},
		/* 0xD9 */ labeled{"RETI", reti()},
		/* 0xDA */ labeled{"JP C, nn", jp(carry, false)},
		/* 0xDB */ labeled{"INVALID OPCODE", invalid()},
		/* 0xDC */ labeled{"CALL C, nn", call(carry, false)},
		/* 0xDD */ labeled{"INVALID OPCODE", invalid()},
		/* 0xDE */ labeled{"SBC A, n", sbcR8(a, paramB())},
		/* 0xDF */ labeled{"RST 18", rst(0x18)},
		/* 0xE0 */ labeled{"LDH (n), A", pipe(a.Read(), paramB(), val(0xFF), writeByte{})},
		/* 0xE1 */ labeled{"POP HL", pop(hl)},
		/* 0xE2 */ labeled{"LDH (C), A", pipe(a.Read(), c.Read(), val(0xFF), writeByte{})},
		/* 0xE3 */ labeled{"INVALID OPCODE", invalid()},
		/* 0xE4 */ labeled{"INVALID OPCODE", invalid()},
		/* 0xE5 */ labeled{"PUSH HL", push(hl)},
		/* 0xE6 */ labeled{"AND n", andR8(a, paramB())},
		/* 0xE7 */ labeled{"RST 20", rst(0x20)},
		/* 0xE8 */ labeled{"ADD SP, d", addSP()},
		/* 0xE9 */ labeled{"JP (HL)", ld(pc.Write(), hl.Read())},
		/* 0xEA */ labeled{"LD (nn), A", pipe(a.Read(), paramW(), writeByte{})},
		/* 0xEB */ labeled{"INVALID OPCODE", invalid()},
		/* 0xEC */ labeled{"INVALID OPCODE", invalid()},
		/* 0xED */ labeled{"INVALID OPCODE", invalid()},
		/* 0xEE */ labeled{"XOR n", xorR8(a, paramB())},
		/* 0xEF */ labeled{"RST 28", rst(0x28)},
		/* 0xF0 */ labeled{"LDH A, (n)", pipe(paramB(), val(0xFF), readByte{}, a.Write())},
		/* 0xF1 */ labeled{"POP AF", pop(af)},
		/* 0xF2 */ labeled{"LD A, (C)", pipe(c.Read(), val(0xFF), readByte{}, a.Write())},
		/* 0xF3 */ labeled{"DI", di()},
		/* 0xF4 */ labeled{"INVALID OPCODE", invalid()},
		/* 0xF5 */ labeled{"PUSH AF", push(af)},
		/* 0xF6 */ labeled{"OR n", orR8(a, paramB())},
		/* 0xF7 */ labeled{"RST 30", rst(0x30)},
		/* 0xF8 */ labeled{"LDHL SP, d", ldHLSPn()},
		/* 0xF9 */ labeled{"LD SP, HL", pipe(hl.Read(), sp.Write(), delay{})},
		/* 0xFA */ labeled{"LD A, (nn)", pipe(paramW(), readByte{}, a.Write())},
		/* 0xFB */ labeled{"EI", ei()},
		/* 0xFC */ labeled{"INVALID OPCODE", invalid()},
		/* 0xFD */ labeled{"INVALID OPCODE", invalid()},
		/* 0xFE */ labeled{"CP n", cpR8(a, paramB())},
		/* 0xFF */ labeled{"RST 38", rst(0x38)},
	}
}

var opCodes = createOpCodeTable()

func nextOpCode() opCode {
	return pipe(paramB(), opCodes)
}

func createExtendedOpCodeTable() opCodeTable {
	return opCodeTable{
		/* 0x00 */ labeled{"RLC B", rlc(b)},
		/* 0x01 */ labeled{"RLC C", rlc(c)},
		/* 0x02 */ labeled{"RLC D", rlc(d)},
		/* 0x03 */ labeled{"RLC E", rlc(e)},
		/* 0x04 */ labeled{"RLC H", rlc(h)},
		/* 0x05 */ labeled{"RLC L", rlc(l)},
		/* 0x06 */ labeled{"RLC (HL)", rlc(hl.Deref())},
		/* 0x07 */ labeled{"RLC A", rlc(a)},
		/* 0x08 */ labeled{"RRC B", rrc(b)},
		/* 0x09 */ labeled{"RRC C", rrc(c)},
		/* 0x0A */ labeled{"RRC D", rrc(d)},
		/* 0x0B */ labeled{"RRC E", rrc(e)},
		/* 0x0C */ labeled{"RRC H", rrc(h)},
		/* 0x0D */ labeled{"RRC L", rrc(l)},
		/* 0x0E */ labeled{"RRC (HL)", rrc(hl.Deref())},
		/* 0x0F */ labeled{"RRC A", rrc(a)},
		/* 0x10 */ labeled{"RL B", rl(b)},
		/* 0x11 */ labeled{"RL C", rl(c)},
		/* 0x12 */ labeled{"RL D", rl(d)},
		/* 0x13 */ labeled{"RL E", rl(e)},
		/* 0x14 */ labeled{"RL H", rl(h)},
		/* 0x15 */ labeled{"RL L", rl(l)},
		/* 0x16 */ labeled{"RL (HL)", rl(hl.Deref())},
		/* 0x17 */ labeled{"RL A", rl(a)},
		/* 0x18 */ labeled{"RR B", rr(b)},
		/* 0x19 */ labeled{"RR C", rr(c)},
		/* 0x1A */ labeled{"RR D", rr(d)},
		/* 0x1B */ labeled{"RR E", rr(e)},
		/* 0x1C */ labeled{"RR H", rr(h)},
		/* 0x1D */ labeled{"RR L", rr(l)},
		/* 0x1E */ labeled{"RR (HL)", rr(hl.Deref())},
		/* 0x1F */ labeled{"RR A", rr(a)},
		/* 0x20 */ labeled{"SLA B", sla(b)},
		/* 0x21 */ labeled{"SLA C", sla(c)},
		/* 0x22 */ labeled{"SLA D", sla(d)},
		/* 0x23 */ labeled{"SLA E", sla(e)},
		/* 0x24 */ labeled{"SLA H", sla(h)},
		/* 0x25 */ labeled{"SLA L", sla(l)},
		/* 0x26 */ labeled{"SLA (HL)", sla(hl.Deref())},
		/* 0x27 */ labeled{"SLA A", sla(a)},
		/* 0x28 */ labeled{"SRA B", sra(b)},
		/* 0x29 */ labeled{"SRA C", sra(c)},
		/* 0x2A */ labeled{"SRA D", sra(d)},
		/* 0x2B */ labeled{"SRA E", sra(e)},
		/* 0x2C */ labeled{"SRA H", sra(h)},
		/* 0x2D */ labeled{"SRA L", sra(l)},
		/* 0x2E */ labeled{"SRA (HL)", sra(hl.Deref())},
		/* 0x2F */ labeled{"SRA A", sra(a)},
		/* 0x30 */ labeled{"SWAP B", swap(b)},
		/* 0x31 */ labeled{"SWAP C", swap(c)},
		/* 0x32 */ labeled{"SWAP D", swap(d)},
		/* 0x33 */ labeled{"SWAP E", swap(e)},
		/* 0x34 */ labeled{"SWAP H", swap(h)},
		/* 0x35 */ labeled{"SWAP L", swap(l)},
		/* 0x36 */ labeled{"SWAP (HL)", swap(hl.Deref())},
		/* 0x37 */ labeled{"SWAP A", swap(a)},
		/* 0x38 */ labeled{"SRL B", srl(b)},
		/* 0x39 */ labeled{"SRL C", srl(c)},
		/* 0x3A */ labeled{"SRL D", srl(d)},
		/* 0x3B */ labeled{"SRL E", srl(e)},
		/* 0x3C */ labeled{"SRL H", srl(h)},
		/* 0x3D */ labeled{"SRL L", srl(l)},
		/* 0x3E */ labeled{"SRL (HL)", srl(hl.Deref())},
		/* 0x3F */ labeled{"SRL A", srl(a)},
		/* 0x40 */ labeled{"BIT 0, B", bit(0, b)},
		/* 0x41 */ labeled{"BIT 0, C", bit(0, c)},
		/* 0x42 */ labeled{"BIT 0, D", bit(0, d)},
		/* 0x43 */ labeled{"BIT 0, E", bit(0, e)},
		/* 0x44 */ labeled{"BIT 0, H", bit(0, h)},
		/* 0x45 */ labeled{"BIT 0, L", bit(0, l)},
		/* 0x46 */ labeled{"BIT 0, (HL)", bit(0, hl.Deref())},
		/* 0x47 */ labeled{"BIT 0, A", bit(0, a)},
		/* 0x48 */ labeled{"BIT 1, B", bit(1, b)},
		/* 0x49 */ labeled{"BIT 1, C", bit(1, c)},
		/* 0x4A */ labeled{"BIT 1, D", bit(1, d)},
		/* 0x4B */ labeled{"BIT 1, E", bit(1, e)},
		/* 0x4C */ labeled{"BIT 1, H", bit(1, h)},
		/* 0x4D */ labeled{"BIT 1, L", bit(1, l)},
		/* 0x4E */ labeled{"BIT 1, (HL)", bit(1, hl.Deref())},
		/* 0x4F */ labeled{"BIT 1, A", bit(1, a)},
		/* 0x50 */ labeled{"BIT 2, B", bit(2, b)},
		/* 0x51 */ labeled{"BIT 2, C", bit(2, c)},
		/* 0x52 */ labeled{"BIT 2, D", bit(2, d)},
		/* 0x53 */ labeled{"BIT 2, E", bit(2, e)},
		/* 0x54 */ labeled{"BIT 2, H", bit(2, h)},
		/* 0x55 */ labeled{"BIT 2, L", bit(2, l)},
		/* 0x56 */ labeled{"BIT 2, (HL)", bit(2, hl.Deref())},
		/* 0x57 */ labeled{"BIT 2, A", bit(2, a)},
		/* 0x58 */ labeled{"BIT 3, B", bit(3, b)},
		/* 0x59 */ labeled{"BIT 3, C", bit(3, c)},
		/* 0x5A */ labeled{"BIT 3, D", bit(3, d)},
		/* 0x5B */ labeled{"BIT 3, E", bit(3, e)},
		/* 0x5C */ labeled{"BIT 3, H", bit(3, h)},
		/* 0x5D */ labeled{"BIT 3, L", bit(3, l)},
		/* 0x5E */ labeled{"BIT 3, (HL)", bit(3, hl.Deref())},
		/* 0x5F */ labeled{"BIT 3, A", bit(3, a)},
		/* 0x60 */ labeled{"BIT 4, B", bit(4, b)},
		/* 0x61 */ labeled{"BIT 4, C", bit(4, c)},
		/* 0x62 */ labeled{"BIT 4, D", bit(4, d)},
		/* 0x63 */ labeled{"BIT 4, E", bit(4, e)},
		/* 0x64 */ labeled{"BIT 4, H", bit(4, h)},
		/* 0x65 */ labeled{"BIT 4, L", bit(4, l)},
		/* 0x66 */ labeled{"BIT 4, (HL)", bit(4, hl.Deref())},
		/* 0x67 */ labeled{"BIT 4, A", bit(4, a)},
		/* 0x68 */ labeled{"BIT 5, B", bit(5, b)},
		/* 0x69 */ labeled{"BIT 5, C", bit(5, c)},
		/* 0x6A */ labeled{"BIT 5, D", bit(5, d)},
		/* 0x6B */ labeled{"BIT 5, E", bit(5, e)},
		/* 0x6C */ labeled{"BIT 5, H", bit(5, h)},
		/* 0x6D */ labeled{"BIT 5, L", bit(5, l)},
		/* 0x6E */ labeled{"BIT 5, (HL)", bit(5, hl.Deref())},
		/* 0x6F */ labeled{"BIT 5, A", bit(5, a)},
		/* 0x70 */ labeled{"BIT 6, B", bit(6, b)},
		/* 0x71 */ labeled{"BIT 6, C", bit(6, c)},
		/* 0x72 */ labeled{"BIT 6, D", bit(6, d)},
		/* 0x73 */ labeled{"BIT 6, E", bit(6, e)},
		/* 0x74 */ labeled{"BIT 6, H", bit(6, h)},
		/* 0x75 */ labeled{"BIT 6, L", bit(6, l)},
		/* 0x76 */ labeled{"BIT 6, (HL)", bit(6, hl.Deref())},
		/* 0x77 */ labeled{"BIT 6, A", bit(6, a)},
		/* 0x78 */ labeled{"BIT 7, B", bit(7, b)},
		/* 0x79 */ labeled{"BIT 7, C", bit(7, c)},
		/* 0x7A */ labeled{"BIT 7, D", bit(7, d)},
		/* 0x7B */ labeled{"BIT 7, E", bit(7, e)},
		/* 0x7C */ labeled{"BIT 7, H", bit(7, h)},
		/* 0x7D */ labeled{"BIT 7, L", bit(7, l)},
		/* 0x7E */ labeled{"BIT 7, (HL)", bit(7, hl.Deref())},
		/* 0x7F */ labeled{"BIT 7, A", bit(7, a)},
		/* 0x80 */ labeled{"RES 0, B", res(0, b)},
		/* 0x81 */ labeled{"RES 0, C", res(0, c)},
		/* 0x82 */ labeled{"RES 0, D", res(0, d)},
		/* 0x83 */ labeled{"RES 0, E", res(0, e)},
		/* 0x84 */ labeled{"RES 0, H", res(0, h)},
		/* 0x85 */ labeled{"RES 0, L", res(0, l)},
		/* 0x86 */ labeled{"RES 0, (HL)", res(0, hl.Deref())},
		/* 0x87 */ labeled{"RES 0, A", res(0, a)},
		/* 0x88 */ labeled{"RES 1, B", res(1, b)},
		/* 0x89 */ labeled{"RES 1, C", res(1, c)},
		/* 0x8A */ labeled{"RES 1, D", res(1, d)},
		/* 0x8B */ labeled{"RES 1, E", res(1, e)},
		/* 0x8C */ labeled{"RES 1, H", res(1, h)},
		/* 0x8D */ labeled{"RES 1, L", res(1, l)},
		/* 0x8E */ labeled{"RES 1, (HL)", res(1, hl.Deref())},
		/* 0x8F */ labeled{"RES 1, A", res(1, a)},
		/* 0x90 */ labeled{"RES 2, B", res(2, b)},
		/* 0x91 */ labeled{"RES 2, C", res(2, c)},
		/* 0x92 */ labeled{"RES 2, D", res(2, d)},
		/* 0x93 */ labeled{"RES 2, E", res(2, e)},
		/* 0x94 */ labeled{"RES 2, H", res(2, h)},
		/* 0x95 */ labeled{"RES 2, L", res(2, l)},
		/* 0x96 */ labeled{"RES 2, (HL)", res(2, hl.Deref())},
		/* 0x97 */ labeled{"RES 2, A", res(2, a)},
		/* 0x98 */ labeled{"RES 3, B", res(3, b)},
		/* 0x99 */ labeled{"RES 3, C", res(3, c)},
		/* 0x9A */ labeled{"RES 3, D", res(3, d)},
		/* 0x9B */ labeled{"RES 3, E", res(3, e)},
		/* 0x9C */ labeled{"RES 3, H", res(3, h)},
		/* 0x9D */ labeled{"RES 3, L", res(3, l)},
		/* 0x9E */ labeled{"RES 3, (HL)", res(3, hl.Deref())},
		/* 0x9F */ labeled{"RES 3, A", res(3, a)},
		/* 0xA0 */ labeled{"RES 4, B", res(4, b)},
		/* 0xA1 */ labeled{"RES 4, C", res(4, c)},
		/* 0xA2 */ labeled{"RES 4, D", res(4, d)},
		/* 0xA3 */ labeled{"RES 4, E", res(4, e)},
		/* 0xA4 */ labeled{"RES 4, H", res(4, h)},
		/* 0xA5 */ labeled{"RES 4, L", res(4, l)},
		/* 0xA6 */ labeled{"RES 4,(HL ", res(4, hl.Deref())},
		/* 0xA7 */ labeled{"RES 4, A", res(4, a)},
		/* 0xA8 */ labeled{"RES 5, B", res(5, b)},
		/* 0xA9 */ labeled{"RES 5, C", res(5, c)},
		/* 0xAA */ labeled{"RES 5, D", res(5, d)},
		/* 0xAB */ labeled{"RES 5, E", res(5, e)},
		/* 0xAC */ labeled{"RES 5, H", res(5, h)},
		/* 0xAD */ labeled{"RES 5, L", res(5, l)},
		/* 0xAE */ labeled{"RES 5, (HL)", res(5, hl.Deref())},
		/* 0xAF */ labeled{"RES 5, A", res(5, a)},
		/* 0xB0 */ labeled{"RES 6, B", res(6, b)},
		/* 0xB1 */ labeled{"RES 6, C", res(6, c)},
		/* 0xB2 */ labeled{"RES 6, D", res(6, d)},
		/* 0xB3 */ labeled{"RES 6, E", res(6, e)},
		/* 0xB4 */ labeled{"RES 6, H", res(6, h)},
		/* 0xB5 */ labeled{"RES 6, L", res(6, l)},
		/* 0xB6 */ labeled{"RES 6, (HL)", res(6, hl.Deref())},
		/* 0xB7 */ labeled{"RES 6, A", res(6, a)},
		/* 0xB8 */ labeled{"RES 7, B", res(7, b)},
		/* 0xB9 */ labeled{"RES 7, C", res(7, c)},
		/* 0xBA */ labeled{"RES 7, D", res(7, d)},
		/* 0xBB */ labeled{"RES 7, E", res(7, e)},
		/* 0xBC */ labeled{"RES 7, H", res(7, h)},
		/* 0xBD */ labeled{"RES 7, L", res(7, l)},
		/* 0xBE */ labeled{"RES 7, (HL)", res(7, hl.Deref())},
		/* 0xBF */ labeled{"RES 7, A", res(7, a)},
		/* 0xC0 */ labeled{"SET 0, B", set(0, b)},
		/* 0xC1 */ labeled{"SET 0, C", set(0, c)},
		/* 0xC2 */ labeled{"SET 0, D", set(0, d)},
		/* 0xC3 */ labeled{"SET 0, E", set(0, e)},
		/* 0xC4 */ labeled{"SET 0, H", set(0, h)},
		/* 0xC5 */ labeled{"SET 0, L", set(0, l)},
		/* 0xC6 */ labeled{"SET 0, (HL)", set(0, hl.Deref())},
		/* 0xC7 */ labeled{"SET 0, A", set(0, a)},
		/* 0xC8 */ labeled{"SET 1, B", set(1, b)},
		/* 0xC9 */ labeled{"SET 1, C", set(1, c)},
		/* 0xCA */ labeled{"SET 1, D", set(1, d)},
		/* 0xCB */ labeled{"SET 1, E", set(1, e)},
		/* 0xCC */ labeled{"SET 1, H", set(1, h)},
		/* 0xCD */ labeled{"SET 1, L", set(1, l)},
		/* 0xCE */ labeled{"SET 1, (HL)", set(1, hl.Deref())},
		/* 0xCF */ labeled{"SET 1, A", set(1, a)},
		/* 0xD0 */ labeled{"SET 2, B", set(2, b)},
		/* 0xD1 */ labeled{"SET 2, C", set(2, c)},
		/* 0xD2 */ labeled{"SET 2, D", set(2, d)},
		/* 0xD3 */ labeled{"SET 2, E", set(2, e)},
		/* 0xD4 */ labeled{"SET 2, H", set(2, h)},
		/* 0xD5 */ labeled{"SET 2, L", set(2, l)},
		/* 0xD6 */ labeled{"SET 2, (HL)", set(2, hl.Deref())},
		/* 0xD7 */ labeled{"SET 2, A", set(2, a)},
		/* 0xD8 */ labeled{"SET 3, B", set(3, b)},
		/* 0xD9 */ labeled{"SET 3, C", set(3, c)},
		/* 0xDA */ labeled{"SET 3, D", set(3, d)},
		/* 0xDB */ labeled{"SET 3, E", set(3, e)},
		/* 0xDC */ labeled{"SET 3, H", set(3, h)},
		/* 0xDD */ labeled{"SET 3, L", set(3, l)},
		/* 0xDE */ labeled{"SET 3, (HL)", set(3, hl.Deref())},
		/* 0xDF */ labeled{"SET 3, A", set(3, a)},
		/* 0xE0 */ labeled{"SET 4, B", set(4, b)},
		/* 0xE1 */ labeled{"SET 4, C", set(4, c)},
		/* 0xE2 */ labeled{"SET 4, D", set(4, d)},
		/* 0xE3 */ labeled{"SET 4, E", set(4, e)},
		/* 0xE4 */ labeled{"SET 4, H", set(4, h)},
		/* 0xE5 */ labeled{"SET 4, L", set(4, l)},
		/* 0xE6 */ labeled{"SET 4, (HL)", set(4, hl.Deref())},
		/* 0xE7 */ labeled{"SET 4, A", set(4, a)},
		/* 0xE8 */ labeled{"SET 5, B", set(5, b)},
		/* 0xE9 */ labeled{"SET 5, C", set(5, c)},
		/* 0xEA */ labeled{"SET 5, D", set(5, d)},
		/* 0xEB */ labeled{"SET 5, E", set(5, e)},
		/* 0xEC */ labeled{"SET 5, H", set(5, h)},
		/* 0xED */ labeled{"SET 5, L", set(5, l)},
		/* 0xEE */ labeled{"SET 5, (HL)", set(5, hl.Deref())},
		/* 0xEF */ labeled{"SET 5, A", set(5, a)},
		/* 0xF0 */ labeled{"SET 6, B", set(6, b)},
		/* 0xF1 */ labeled{"SET 6, C", set(6, c)},
		/* 0xF2 */ labeled{"SET 6, D", set(6, d)},
		/* 0xF3 */ labeled{"SET 6, E", set(6, e)},
		/* 0xF4 */ labeled{"SET 6, H", set(6, h)},
		/* 0xF5 */ labeled{"SET 6, L", set(6, l)},
		/* 0xF6 */ labeled{"SET 6, (HL)", set(6, hl.Deref())},
		/* 0xF7 */ labeled{"SET 6, A", set(6, a)},
		/* 0xF8 */ labeled{"SET 7, B", set(7, b)},
		/* 0xF9 */ labeled{"SET 7, C", set(7, c)},
		/* 0xFA */ labeled{"SET 7, D", set(7, d)},
		/* 0xFB */ labeled{"SET 7, E", set(7, e)},
		/* 0xFC */ labeled{"SET 7, H", set(7, h)},
		/* 0xFD */ labeled{"SET 7, L", set(7, l)},
		/* 0xFE */ labeled{"SET 7, (HL)", set(7, hl.Deref())},
		/* 0xFF */ labeled{"SET 7, A", set(7, a)},
	}
}

var irqHandlerOpCode = pipe(
	delay{},
	delay{},
	delay{},
	opCodeFn(func(c *CPU, state *ocState) {
		c.sp -= 2
		addr := c.sp
		val := c.pc

		state.pushB(byte(val))
		state.pushW(addr)

		state.pushB(byte(val >> 8))
		state.pushW(addr + 1)
	}),
	writeByte{ /*hi*/ },
	opCodeFn(func(c *CPU, state *ocState) {
		irq := c.mmu.GetCurrentIterrupt()
		c.pc = irq.Address()
		c.ime = false
	}),
	writeByte{ /*lo*/ },
)
